server:
  port: 8071

spring:
  application:
    name: "underwriter-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: "${DB_USERNAME:dev}" # Default to 'dev' if not specified
    password: "${DB_PASSWORD:mypassword}" # Default to 'mypassword' if not specified
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/aline?useSSL=false&serverTimezone=UTC"
    initialization-mode: always

app:
  email:
    enable: true
    from: "no-reply@alinefinancial.com"
  aws:
    email:
      template-bucket-name: "aline-email-templates"
    credentials:
      access-key-id: "${AWS_ACCESS_KEY_ID}" 
      secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
  landing-portal: "${PORTAL_LANDING_URL}"
  member-dashboard: "${PORTAL_DASHBOARD_URL}"
  security:
    secret-key: "ThisIsAGreatSecretKey!!!" 
    jwt:
      secret-key: "eyJhbGciOiJIUzIlNiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMONTY30DkwIiwibmFtZSI6IkpvaG4gRG91liwiaWF0IjoxNTE2MjM5MDIyfQ.Sf1KxwRJSMeKKF2QT4fwpMeJf36P0k6yJV_adQssw5c" 


logging:
  level:
    root: INFO
    com.aline: DEBUG

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"
