#!/bin/bash
export DB_USERNAME=root
export DB_PASSWORD=12345678
export DB_HOST=localhost
export DB_PORT=3306
export DB_NAME=aline
export APP_USER_ACCESS_KEY=ThisIsAGreatSecretKey!!!
export APP_USER_SECRET_KEY=ThisIsAGreatSecretKey!!!
export PORTAL_LANDING=00
export PORTAL_DASHBOARD=00
export PORTAL_ADMIN=00
export ENCRYPT_SECRET_KEY=ThisIsAGreatSecretKey!!!
export JWT_SECRET_KEY="eyJraWQiOiI5NTk3YzBjYS1lYWUwLTRjYzMtYjlkNC0wYmNhN2IzYTNkMzEiLCJhbGciOiJFUzI1NiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.WILPE-k1MAyMoELcPk_5LpbItZe0adLnFpHXikuJrT0b3DDQDKc34_yO8LW-8zJrxO9jOP4n_FYlafGoZzU1Kw"

# Gateway specific vars
export APP_SERVICE_HOST=http://localhost 