apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-account-microservice
  labels:
    app: aline-account-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-account-microservice
  template:
    metadata:
      labels:
        app: aline-account-microservice
    spec:
      containers:
      - name: aline-account-microservice
        image: direstbounty/capstone:account-service
        ports:
        - containerPort: 8074
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/aline
        - name: SPRING_DATASOURCE_USERNAME
          value: 'root'
        - name: SPRING_DATASOURCE_PASSWORD
          value: '12345678'
